### ISSUE TITLE
A lot of times clicking on the menu button doesn't have any effect.

### ISSUE THREAD

**Issue by asereze** [martinchodev/Diaspora-Native-WebApp#10]
Sometimes (if it's already slowed down) the menu opens up after a few seconds, and sometimes you have to click again.

**Comment by mdev88** [comment]
This seems to be a problem with the mobile version of Diaspora, because that menu is part of the web, not an external menu from the app.
If the phone or the connection is slowed down, this should happen to any kind of link, not just the menu.
I am unable to reproduce this problem so far.
