### ISSUE TITLE
Sometimes you can't open comments/favourites (both in sfw and nsfw posts) and nsfw images

### ISSUE THREAD

**Issue by asereze** [martinchodev/Diaspora-Native-WebApp#12]
There is a problem with the possibility to show comments/favourites (both in sfw and nsfw posts) and nsfw images. When you try to click, a lot of times nothing happens. You have to click dozens of times, and when it works it loads things only after a lot of seconds (like from 10 to 30, usually).

**Comment by mdev88** [comment]
I am unable to reproduce this error, and it seems related to the other issues created by you. I don't know if it's a connection problem, a phone resources problem or a touch screen problem or something like that.

Let's wait and see if anybody else experiences the same problems and hope to gather more information about them.
