### ISSUE TITLE
Multiple accounts?

### ISSUE THREAD

**Issue by ghost** [martinchodev/Diaspora-Native-WebApp#19]
It would be nice if app could allow user to switch between multiple accounts.

**Comment by mdev88** [comment]
The Diaspora API is on ist's way, so I don't think I will be adding much more features to this webapp for now. I add this to the feature list anyway.

**Comment by ghost** [comment]
You want to move to a native app? Note that there is already a native app [here](https://github.com/tilucifer/DiaspDroid) but its development seems to be stopped.

**Comment by mdev88** [comment]
Sorry, when I said "native" I ment "not a webapp". This is already a native Android app, in the sense that is not made with some framework like Phonegap, but with the Android SDK, in Java, blah blah blah.

When the Diaspora API is stable (and documented) enough, I might try to make a new app that takes advantage of the API, yes.

I think this one is quite usable in the current state. I will keep adding stuff to it, but for the moment I think I will wait to see what happens with the API.

**Comment by ghost** [comment]
> When the Diaspora API is stable (and documented) enough, I might try to make a new app that takes advantage of the API, yes.

Nice. I'm developing [Griaspora](https://github.com/AugierLe42e/Griaspora), a Groovy library that is meant to enable the use of the diaspora API for Android applications. It is for now in a very early stage as we are still changing the API but I continue to work on it.

**Comment by mdev88** [comment]
Excellent, we'll keep in touch then :)
