### ISSUE TITLE
Buttons are stuck until page is completely loaded

### ISSUE THREAD

**Issue by ghost** [martinchodev/Diaspora-Native-WebApp#2]
Not sure about the details but you should probably look at Android's [Async Tasks](https://developer.android.com/reference/android/os/AsyncTask.html) or even start a new thread to load the page. You can find a tuto [here](http://www.vogella.com/tutorials/AndroidBackgroundProcessing/article.html) if needed ;)

**Comment by mdev88** [comment]
Hello Augier. I am aware of AsyncTasks :D
Could you tell me what buttons are locked while loading the page? The "reload" button in the title bar? The options menu? I have tried those while changing pages but it didn't freeze for me.

When you open the app, a progress dialog should appear that is non-cancelable. Until it finishes, you won't be able to interact with the UI, and that is correct.
On the other hand, I think that the WebView (the element that loads the web pages) works in an asynchronous way by default, so it shouldn't interfere with the rest of the UI.

Maybe what you mean is the app should display some kind of progress bar or dialog when the pages are still loading. I am actually working on that, but haven't found a satisfactory solution yet, but it's something that will be functional soon.

Thanks for the feedback!

**Comment by ghost** [comment]
> Could you tell me what buttons are locked while loading the page?

Well, basically all the links. It happens when something heavy must load or when the network is shitty :D
I talk about the button inside the page, not your app's ;)

**Comment by mdev88** [comment]
Oh, I get it now. Thanks for the clarification.

I don't think I have much control over what's happening inside of the WebView while it loads other than knowing it is loading and when it finishes. I will investigate the issue anyway and see if I can improve this.

Thanks

**Comment by ghost** [comment]
NP. FYI, there is not such a problem on Flaburgan's webapp which runs on Firefox plateform.

**Comment by mdev88** [comment]
Ok, thanks for the info.

**Comment by mdev88** [comment]
I added a loading dialog while the page is still loading.
I deliberately allow it to be cancelled (the page keeps loading but you can start browsing it if you like) and also, it shows until 50% of the page is loaded. I did this to reduce the time you have to wait until you can actually use the app.

**Comment by ghost** [comment]
Thx
