### ISSUE TITLE
Hide menu bar

### ISSUE THREAD

**Issue by ghost** [martinchodev/Diaspora-Native-WebApp#20]
The menu bar takes a lot of space on the screen. I personnaly have a big screen so it is not a big deal but it must be really disturbing for smaller screens.

![screenshot_2015-08-04-09-01-05](https://cloud.githubusercontent.com/assets/3429231/9055125/f9ceb830-3a87-11e5-84dc-b778476fe473.png)

**Comment by mdev88** [comment]
Yup, it's been suggested and it's on the feature list for when I switch to Material Design.

**Comment by moshpirit** [comment]
Version 1.6.1 (current version on F-droid) hide it most of the times, it still needs some fixes but I really appreciate the change :-)
