### ISSUE TITLE
Suggestion: Use SubsamplingScaleImageView and make Images downloadable

### ISSUE THREAD

**Issue by vanitasvitae** [martinchodev/Diaspora-Native-WebApp#22]
Hi
Im missing the function to zoom into photos in posts and also often i want to save some photos.

Could you use this as image view?:
https://github.com/davemorrissey/subsampling-scale-image-view
You can zoom into images of any resolution without getting memory issues :)

**Comment by mdev88** [comment]
It would be nice, but I'm not sure if I can use it with the images shown inside the webview. I think this only works with local images. I will give it a look.

Thanks

**Comment by mdev88** [comment]
I cannot use SubsamplingScaleImageView in this web app. I am looking for another solution, but no luck so far.
