### ISSUE TITLE
sharing from fennec makes both fennec and diaspora app to crash

### ISSUE THREAD

**Issue by pravi** [martinchodev/Diaspora-Native-WebApp#27]
1.5.5 from fdroid and fennec fdroid 40.0. CyanogenMod 12. Yu Yuphoria phone. It was working fine till 1.5.4. I think it works first time the app is started.

**Comment by mdev88** [comment]
Hello

If you have a rooted phone, could you send me a log generated with CatLog
while the app crashes?

Thanks

2015-09-26 8:11 GMT-03:00 Praveen Arimbrathodiyil notifications@github.com
:

**Comment by mdev88** [comment]
Nevermind, I can reproduce the error. Thank you.

2015-09-26 8:59 GMT-03:00 Martín V juangalt12@gmail.com:

**Comment by mdev88** [comment]
I have found the problem and fixed it. I am publishing an update right now.
Thanks for the heads up :)

2015-09-26 8:59 GMT-03:00 Martín V juangalt12@gmail.com:
