### ISSUE TITLE
Reload by "swiping down" the screen

### ISSUE THREAD

**Issue by moshpirit** [martinchodev/Diaspora-Native-WebApp#28]
"Reload" could be done by ["swiping down" the TL](https://www.bignerdranch.com/blog/implementing-swipe-to-refresh/) so it's an item that is not needed to include in the menu anymore.

**Edit**: the lateral panel is great, so nothing to say about it.

**Comment by blausand** [comment]
+1
Of course.
Swiping left/right could also be used tonavigate between different streams. There's still two menus too much.

(Keep in mind this wouldn't collide with the nice sidebar when you define 15% border from where to access the menu.)

**Comment by sedrubal** [comment]
:+1: for sliding down to reload

**Comment by moshpirit** [comment]
> Swiping left/right could also be used tonavigate between different streams. There's still two menus too much.

I think that we probably have too much TLs and that's may be confusing.

**Comment by mdev88** [comment]
I don't think this is possible with a webview. If anyone knows how to do it, please let me know. 
Until that, or a Diaspora API is released and a true native APP can be created, I close this issue.

**Comment by blausand** [comment]
Have you examined the new API, Martin? Are you planning to sketchup a native App?
I'd be glad to hear about it.

**Comment by mdev88** [comment]
I am. Unfortunately I have very little spare time, so I couldn't say when. Maybe is the next weekend, maybe the next month...
