### ISSUE TITLE
Basic functions no longer working since 1.5.1 or .2

### ISSUE THREAD

**Issue by benedetto** [martinchodev/Diaspora-Native-WebApp#30]
Setup:
- Diaspora Native WebApp v. >1.5.1 from f-droid
- Android 4.2.2
- Account on pod.geraspora.de

Since one of the recent updates of the app from f-droid, it is basically unuseable to me as the most basic functions are no longer working. Symptoms are:
In stream view
- Hitting the like button (heart) gives a "500: internal sever error";
- Hitting the share button results in a "404: page not found";
- in NSFW posts that contain an image the image is displayed shortly and partially during loading of the stream and are then greyed out. The "Show post" link does not cause any change.

Hitting the "x reactions" link under a post in the stream view does lead to a basically empty page which contains some numbers (something like "2 0 0" – which I guess are the counts of likes, reshares and comments) and a hyperlink named "comment". Clicking it, I end up on another white page with a tiny (20 characters wide, 2 lines high) input field and a send button.

All this makes the app quite unuseable since I can neither like nor share anything and commenting is at best inconvenient.

**Comment by mdev88** [comment]
Do you still have this problem with the latest versions?

**Comment by benedetto** [comment]
At the moment everything runs smoothly. The interesting point is, the mentioned stuff disappeared all of a sudden without Diaspora Native WebApp being updated (maybe an update on the server side?). Just as I was about to close this bug as no longer occurring, it came back and disappeared again after some days (again without an update of the app). As said, at the moment everything is fine and if you want to, you can close this one.

**Comment by mdev88** [comment]
Yes, my guess is that maybe something changed in the server, or maybe your pod updated the Diaspora version or something like that.
Closing.
