### ISSUE TITLE
Disable zoom

### ISSUE THREAD

**Issue by ghost** [martinchodev/Diaspora-Native-WebApp#36]
When switching to desktop view, the application displays the zoom buttons on bottom right corner and openning the publisher automatically zooms on it.

**Comment by mdev88** [comment]
Can you explain what is the problem with that exactly? 
The default behaviour when clicking on a text view is to zoom in on it so that you can better read what you type.

**Comment by ghost** [comment]
> The default behaviour when clicking on a text view is to zoom in on it so that you can better read what you type.

Would be nice to disable this behaviour. It does not do that on mobile view and desktop view is optimised for small screens like phone so it's really not necessary.
