### ISSUE TITLE
prefix # on hashtag searchrewuest results in internal server error

### ISSUE THREAD

**Issue by vanitasvitae** [martinchodev/Diaspora-Native-WebApp#37]
Hi
I believe this is more a diaspora issue, but it can be fixed in the webapp as well.

When the user tries to search for a hashtag and prepands a '#' to the search term (like one is used to from diaspora), my pod answers with a 500 Internal Server Error.

I guess this is, because the webapp adds a '#' to tge search term when searching for hashtags, so the search becomes '##something', which results in the error mentioned above.

One solution would be to remove all # from the search term before forwarding it to diadpora with a prepanded #.

**Comment by mdev88** [comment]
I now remove any # character from the input text and I think that's enough to fix this issue.
This change will be up in the next update.
