### ISSUE TITLE
App crashes the phone when Wi-Fi is off

### ISSUE THREAD

**Issue by pizzamaker** [martinchodev/Diaspora-Native-WebApp#4]
When trying to open the app with the Wi-Fi turned off, it crashes the phone, requiring a reboot.

Bug noticed on v1.2

**Comment by mdev88** [comment]
Added to the bugs list. Will release a fix in the next update.

**Comment by mdev88** [comment]
I just published cersion 1.3 which should take care of this issue. 
If it persists, please open a new issue with information about your device (model and Android version if possible), and if you installed it from Google Play or from another source (F-Droid or APK)
