### ISSUE TITLE
Crashing on Marshmallow

### ISSUE THREAD

**Issue by ghost** [martinchodev/Diaspora-Native-WebApp#40]
Here is my logcat.

[2015-12-22-06-32-31.txt](https://github.com/martinchodev/Diaspora-Native-WebApp/files/69327/2015-12-22-06-32-31.txt)

Device infos:
build.board: smdk4210
build.bootloader: unknown
build.brand: Samsung
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: GT-N7000
build.display: cm_n7000-userdebug 6.0.1 MMB29M d9047f876b test-keys
build.fingerprint: samsung/GT-N7000/GT-N7000:4.0.3/IML74K/ZCLP6:user/release-keys
build.hardware: smdk4210
build.host: pc
build.id: MMB29M
build.manufacturer: samsung
build.model: GT-N7000
build.product: GT-N7000
build.radio: unknown
build.serial: 0019999004943f
build.tags: test-keys
build.time: 1450684093000
build.type: userdebug
build.user: bauner
version.codename: REL
version.incremental: d9047f876b
version.release: 6.0.1
version.sdk_int: 23

Greetings
scoute-dich

**Comment by klonamy** [comment]
It it is also crashing in ther App-Version 1.7.2 on a OnePlus One with the CM12.1-YOG4PAS3JL (Android 5.1.1).

---

OOT: @scoute-dich How i make a logcat at my unrooted phone or is that not possible?

**Comment by verymilan** [comment]
how to reproduce?
successful tested on `CM13.0-20151211-UNOFFICIAL-Sultan-bacon` (OnePlus One).
no crashes.

**Comment by klonamy** [comment]
I am just starting the app and it crashes.
Cache or App deletion and reinstall didn't help either.

**Comment by ghost** [comment]
OOT: @klonamy I used:
https://f-droid.org/repository/browse/?fdfilter=logcat&fdid=com.nolanlawson.logcat
alternatives:
https://f-droid.org/repository/browse/?fdfilter=monitor&fdid=com.eolwral.osmonitor
https://play.google.com/store/apps/details?id=com.pluscubed.matlog

OOT: @tchncs I just can't start the app. Clean install, wiped data and cache. Not even the splashscreen starts. :-(

**Comment by mdev88** [comment]
Please confirm the app doesn't crash anymore in version 1.7.3.

**Comment by klonamy** [comment]
It is not crashing anymore.

**Comment by mdev88** [comment]
Allright! Closing...
