### ISSUE TITLE
Colors not related to diaspora

### ISSUE THREAD

**Issue by sedrubal** [martinchodev/Diaspora-Native-WebApp#45]
I think the current colors (magenta and yellow) are not really related to diaspora. Is it possible to use the selected colorscheme of diaspora (original dark, dark green, magenta, Egyptian blue, original white background) for the app? Or do you want to use diaspora colors?

**Comment by moshpirit** [comment]
Is it possible to include themes? that probably would make it cooler since we could actually customise the app.

**Comment by mdev88** [comment]
Changed the colors. I hope you don't die of boredom.

**Comment by sedrubal** [comment]
:D thanks. I'm looking forward...

**Comment by moshpirit** [comment]
> I hope you don't die of boredom.

I'm sorry if we sound rude, I'd love to have themes or something to change it and enjoy as much colours as possible but it's true that the last pink/yellow combination wasn't the best for me.

EDIT: and thanks!
