### ISSUE TITLE
Move search to title bar

### ISSUE THREAD

**Issue by sedrubal** [martinchodev/Diaspora-Native-WebApp#47]
Many apps have a magnifier icon in title bar and when tabbing this icon a text field appears. I think this could be a nicer solution than adding the search function to the '+' button menu (because you don't add something when you search something...) Then you can show recently searched words and so on. To separate tags and people you can maybe add a drop down to the search bar or you solve this like  [jonan/ForkHub](https://github.com/jonan/ForkHub) does...

**Comment by mdev88** [comment]
Done. Please check the next update.
