### ISSUE TITLE
Add share function

### ISSUE THREAD

**Issue by sedrubal** [martinchodev/Diaspora-Native-WebApp#48]
I'd find it great if there would be a share function to share diaspora posts to other apps...

**Comment by teslasmoustache** [comment]
seconded.

**Comment by djibux** [comment]
That would indeed be awesome, especially to add URLs to a read-later app (wallabag, pocket or any other).

**Comment by mdev88** [comment]
I'll look into it. Thanks.

**Comment by ghost** [comment]
Hi,

perhaps you can close this issue with "my" share menu. I have a code snippet on gist. Perhaps gist is a possibility to work together. We can share code and discuss on out... Anyway here is the link.

https://gist.github.com/ad24601df5bf4a8c8044

It's the first time I try gist, so I don't know of it's fitting to out tries. But let's check it out. ;-)
