### ISSUE TITLE
Hide the (+) button

### ISSUE THREAD

**Issue by moshpirit** [martinchodev/Diaspora-Native-WebApp#49]
It's a useful button, don't get me wrong but I think that shouldn't be visible all the time because it uses some space and it bothers me sometimes because it's too close to the "comment" button and hide the text sometimes. 

My proposal is to hide it when we are navigating down the screen (↓) but if we go up again (↑) then showing it.

I think I saw someone else saying this but I can't find the issue so here I am. Thank you so much for your great application!! :)

**Comment by sedrubal** [comment]
:+1:

**Comment by mdev88** [comment]
I'm not sure this is possible because the swiping up and down occurs inside the webview and capturing that kind of events is tricky.
When the Diaspora API is released and change the webview for a listview or recycler view I will do this.

**Comment by teslasmoustache** [comment]
Two possibilities I can think of in the meantime (until the API comes out and you can come up with something better:

1: Swipe up from the bottom edge. FirefoxOS has a convention of a partly hidden navigation menu at the bottom which you can swipe up to reveal. I'm not suggesting an entire menu, Just something more out of the way. Something as unobtrusive as that thing in the lower left-hand corner of the Gnome desktop.

2: Add it to the menu in the upper left that you already have. It might not be the best design choice, but at least it gets that thing out of the way.

**Comment by mdev88** [comment]
I haven't find a way to do this yet, but I have changed the behaviour so that the + button is less intrusive.
Please try the latest version (1.8.3)

**Comment by sedrubal** [comment]
Thank you for your active developement :+1: it's amazing ;)

**Comment by mdev88** [comment]
I hope you're not being sarcastic. I wouldn't call it "active" at all, but thanks anyway.

**Comment by sedrubal** [comment]
Oh no I'm not sarcastic. I often write issues but there are very few projects someone really cares about my requests ;)

Back to topic: i couldn't test it yet as it is not yet available in fdroid...

**Comment by moshpirit** [comment]
Thanks for the support!! :)

**Comment by lbarthelemy** [comment]
Hi,

First, thank you for the application and the support.

I just wanted to show that even with version 1.8.3 from fdroid on Nexus5 (Android 6.0.1), the (+) button can still have unfortunate screen placement, for example while browsing images: it is displayed over the right arrow to go to the next image:

![screenshot_20160121-224225](https://cloud.githubusercontent.com/assets/197864/12498197/ff1d53d8-c0a0-11e5-81d4-1e5ec7753636.png)

Regards,

**Comment by mdev88** [comment]
Thanks, I'll take a look at it.
