### ISSUE TITLE
not all the pods 

### ISSUE THREAD

**Issue by moshpirit** [martinchodev/Diaspora-Native-WebApp#5]
It misses pod.babillage.org

**Comment by mdev88** [comment]
That pod is not listed in https://podupti.me/ and that's why it does not appear on the list. I only add the pods from that list, and only those marked as secure.

In the next update you will have the ability to manually enter the pod domain and use it, even if it's not on the list.

**Comment by moshpirit** [comment]
Great, thanks! Have you got in mind when is it going to be released?

**Comment by mdev88** [comment]
Probably by the end of this week, it depends on how much brain power I have left by then :)

**Comment by moshpirit** [comment]
Good, thank you!! :D

**Comment by mdev88** [comment]
I just published version 1.3 which includes the possibility to connect to custom pods which are not included on the list.
