### ISSUE TITLE
Unable To Change Pods? (v1.8.2 from Play Store)

### ISSUE THREAD

**Issue by bambams** [martinchodev/Diaspora-Native-WebApp#50]
I suspect that the app is silently failing to "change" pods. I am trying to change to pod.orkz.net, but the background behind the sign-in form continues to say "Diaspora\* @ Oude RKZ Groningen". I assume it is selecting a different pod than the one I selected/typed (neither works). When I select it I'm prompted, "Do you want to use the pod:pod.orkz.net?" I choose "yes" and it seems nothing changes. I'm assuming the pod hasn't changed because I can't log in. I'm fairly certain I'm entering the correct credentials, but it always fails. _Append_: I have a Galaxy S5 if that makes any difference, though I don't see why it would.

**Comment by bambams** [comment]
Update: I am able to change to various random pods successfully, but it seems this particular pod (pod.orkz.net) doesn't work. That or it identifies itself oddly and I'm just entering the wrong credentials. Can anybody else test it?

**Comment by mdev88** [comment]
Please check if you still have this problem with the latest update (1.8.3). I have fixed some cache issues and I think that might fix this issue.
