### ISSUE TITLE
F-Droid?

### ISSUE THREAD

**Issue by Clonewayx** [martinchodev/Diaspora-Native-WebApp#56]
App is not in F-Droid.
Link from README.md https://f-droid.org/repository/browse/?fdfilter=diaspora&fdid=ar.com.tristeslostrestigres.diasporanativewebapp is not valid.

**Comment by vanitasvitae** [comment]
This app has been merged with dandelion*.

You can find dandelion* in FDroid: https://f-droid.org/repository/browse/?fdfilter=dandelion&fdid=com.github.dfa.diaspora_android

**Comment by Clonewayx** [comment]
Such a pity. dandelion require Android 4.2 and higher ...

**Comment by vanitasvitae** [comment]
That's unfortunately true. We increased the min API level in order to circumvent a serious security issue in Androids WebView in combination with javascript.

Maybe we should offer a fallback apk for older devices, which is declared as "use-under-own-risk".
