### ISSUE TITLE
Trim whitespace after domain 

### ISSUE THREAD

**Issue by Siedlerchr** [martinchodev/Diaspora-Native-WebApp#58]
When I entered a domain my auto suggestion added a whitespace I didn't see and resulted in errors.
It was shown as %20. So I think trimming the domain field may be useful

**Comment by mdev88** [comment]
Sorry, this app is no longer under development.

**Comment by mdev88** [comment]
I have decided to continue maintaining this app, so I will take a look of this issue and fix it in the next release. Cheers.

**Comment by mdev88** [comment]
Fixed in next release: version 1.9
