### ISSUE TITLE
Ignore a user 

### ISSUE THREAD

**Issue by Cordelya** [martinchodev/Diaspora-Native-WebApp#59]
There is no apparent way to add a user to the ignore list. This may be an issue with d* itself - I went to my pod site in a mobile browser and had to switch to the desktop version to get an ignore button. If this is, in fact something that has to be fixed in the d* codebase, please let me know so I can add an issue there.

**Comment by mdev88** [comment]
That's correct. That is a D* feature, one I cannot add to this humble web app, which is no longer under development.
