### ISSUE TITLE
allow sharing links from browser

### ISSUE THREAD

**Issue by pravi** [martinchodev/Diaspora-Native-WebApp#7]
It should be registered as capable of accepting share requests and it should post it using the bookmarklet url.

**Comment by mdev88** [comment]
Yes, it's in the roadmap :)

**Comment by mdev88** [comment]
Done

**Comment by pravi** [comment]
It does not work, if the app is already open. We have to exit app and then share again.

**Comment by mdev88** [comment]
Can you describe what is actually the problem? 

Note that problems related with a slow or bad internet connection or problems in a specific pod are beyond my control. Also, be sure to be using the latest version of the app. Please verify those things and confirm the problem still exists.

I cannot reproduce this error. I open the app, then a browser, then share some page to Diaspora and the app opens in the compose screen with all the info about the link being shared is there.

You can follow the tag #ViaDiasporaNativeWebApp to see a lot of people already using this function succesfully, so it might be a specific problem with your phone/tablet/Internet connection/pod.

Thanks.

**Comment by pravi** [comment]
It is problem with slow internet connection. You can set proper timeout and retry options like a browser do.

**Comment by mdev88** [comment]
But what is the problem exactly? It fails to load the compose page? It takes too long but works? ...

**Comment by pravi** [comment]
I just tried on a good connection and got the same problem. I could post once successfully. But when I try to share a link for a second time, it just brings the diadpora app to foreground. It does not show the bookmarklet publisher screen. I'm using fennec fdroid browser.

**Comment by mdev88** [comment]
I can confirm that. It's not a connection issue, it happens after you have shared at least one time.
Reopened.
